### ISSUE TITLE
WIP `rlay-generate`: Request for Comment

### ISSUE THREAD

**Issue by MichaelHirn** [rlay-project/rlay-utils#2]
### Simple Summary

`rlay-generate` is a CLI command, that auto-generates a convenient `js` client to interact with `rlay` and the underlying database based on the schema of the application.

#### Schema

```
HTTPConnection Class
HTTPRequest Class

payload DataProperty

requests ObjectProperty
```

### Create Entity

**`createX (body)`**: where **X** is the name of a `Class` and **body** is an `Object` where its keys are the names of the `DataProperties` or `ObjectProperties`.

```JS
const rlay = require('./generated/rlay-client')

// Create a new HTTP connection
async function main() {  
  const newUser = await rlay.createHTTPConnection({ 
   $inherent: { id: 'abc' },
   payload: JSON.stringify(data)
  })
}
```

### Query Single Entity

**`X (body)`**: where **X** is the name of a `Class` and **body** is an `Object` where its keys are the names of the `DataProperties` or `ObjectProperties`.

```JS
const rlay = require('./generated/rlay-client')

// Create a new HTTP connection
async function main() {  
  const newUser = await rlay.HTTPConnection({ cid: cid })
}
```

### Query Multiple Entities

**`Xs (body)`**: where **X** is the name of a `Class` and **body** is an `Object` where its keys `where` and the value is a `QUERY` instance.

```JS
const rlay = require('./generated/rlay-client')

// Create a new HTTP connection
async function main() {  
  const newUser = await rlay.HTTPConnections({ where: QUERY })
}
```

### Update Entity/Entities

**`updateX (body)`**: where **X** is the name of a `Class` and **body** is an `Object` where its valid keys are `where` and the value is a `QUERY` instance and `data` and the value is an `Object` where its keys are the names of the `DataProperties` or `ObjectProperties` .

```JS
const rlay = require('./generated/rlay-client')

// Create a new HTTP connection
async function main() {  
  const newUser = await rlay.updateHTTPConnection({
    where: QUERY,
    data: { payload: JSON.stringify(data) }
  })
}
```

### Delete Entity/Entities

**`deleteX (body)`**: where **X** is the name of a `Class` and **body** is an `Object` where its valid keys are `where` and the value is a `QUERY` instance and `data` and the value is an `Object` where its keys are the names of the `DataProperties` or `ObjectProperties` .

```JS
const rlay = require('./generated/rlay-client')

// Create a new HTTP connection
async function main() {  
  const newUser = await rlay.updateHTTPConnection({
    where: QUERY,
    data: { payload: JSON.stringify(data) }
  })
}
```

### Open Questions:

- What is a `QUERY` instance?
- How do you handle more complex `QUERY`s, e.g. `IS NOT EMPTY`, `>=`, `INCLUDES`
- How do you handle pagination? (E.g. when `QUERY` result is large)

### Implementation

Reference: #1

**Comment by MichaelHirn** [comment]
Discussion results with @hobofan:

- skip implementation of `update` and `delete` functionality, due to `rlay`'s architecture
- align interface design closer with that of `mongo` clients instead of `graphql` clients
  - which means `.createX()` -> `.X.create()`, `.X()` -> `.find()`, `.X()` -> `.findAll()`
- naming: `inherent` becomes `properties`.

**Comment by hobofan** [comment]
All the important bits have been added in #1. Will open new issues as necessary.
