### ISSUE TITLE
Different property values on Individual.create yield the same CID

### ISSUE THREAD

**Issue by hobofan** [rlay-project/rlay-utils#64]
Follow up to #1 .

Repo to reproduce: https://github.com/hobofan/rlay-utils-repro/tree/fe349c4ca80ec79c22b2b2200ab9ac1c96a63d8f

**Comment by hobofan** [comment]
This line just creates empty entities for each of the properties if I understand it correctly:
https://github.com/rlay-project/rlay-utils/blob/61865b77bfc72360fce27c2ec82b54cd70bf7a32/rlay-client-lib/src/rlay/individual.js#L47

**Comment by MichaelHirn** [comment]
Yeah, you could be right.

`.create` doesn't get any params. Should be something like?

```js
propertyEntityPromises.push(this.client[propertyName].create({
  property: propertyKeys[propertyName]
}));
```
